"""Run the whole ingest flow on this machine, with no AWS account.

1. start a moto S3 emulator on localhost;
2. create the landing and lake buckets with their security defaults;
3. upload the monthly file to the landing bucket (what a scheduled fetcher or
   a person would do);
4. build the S3 ObjectCreated event and call the Lambda handler with it (in
   AWS, S3 would invoke the function itself);
5. send the same event again to prove a duplicate delivery is skipped;
6. query the curated Parquet in place with DuckDB, as Athena would;
7. write `results/ingest_summary.md`.

Usage: python scripts/download_data.py && python scripts/run_local.py
"""
import json
import sys
from pathlib import Path

import boto3
import duckdb
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lake import config  # noqa: E402
from lake.handler import lambda_handler  # noqa: E402
from lake.infra import ensure_buckets, local_aws, s3_put_event  # noqa: E402

RAW = ROOT / "data" / "raw" / "pp-monthly-update.csv"
META = ROOT / "data" / "raw" / "source.json"
OUT = ROOT / "results" / "ingest_summary.md"
REGION = "eu-west-2"  # London


def lake_listing(s3) -> pd.DataFrame:
    objs = s3.list_objects_v2(Bucket=config.lake_bucket()).get("Contents", [])
    return pd.DataFrame([{"key": o["Key"], "bytes": o["Size"]} for o in objs])


def query_curated(con, release: str) -> pd.DataFrame:
    path = f"s3://{config.lake_bucket()}/{config.CURATED_PREFIX}*/*.parquet"
    return con.sql(f"""
        SELECT record_status, count(*) AS rows,
               round(median(price)) AS median_price
        FROM read_parquet('{path}', hive_partitioning = true)
        WHERE release = '{release}'
        GROUP BY record_status ORDER BY record_status
    """).df()


def main() -> None:
    if not RAW.exists() or not META.exists():
        sys.exit("raw file missing: run `python scripts/download_data.py` first")
    source = json.loads(META.read_text())
    release = source["release"]

    with local_aws(region=REGION) as endpoint:
        s3 = boto3.client("s3")
        created = ensure_buckets(s3, REGION)

        key = config.landing_key(release)
        s3.upload_file(str(RAW), config.landing_bucket(), key)
        head = s3.head_object(Bucket=config.landing_bucket(), Key=key)
        event = s3_put_event(config.landing_bucket(), key, head["ETag"].strip('"'),
                             head["ContentLength"], REGION)

        first = lambda_handler(event)["results"][0]
        second = lambda_handler(event)["results"][0]  # duplicate delivery

        listing = lake_listing(s3)
        rejected = pd.read_csv(s3.get_object(
            Bucket=config.lake_bucket(), Key=config.quarantine_key(release))["Body"], dtype=str)

        con = duckdb.connect()
        con.execute("LOAD httpfs")
        con.execute(f"""CREATE SECRET (TYPE S3, KEY_ID 'local-test', SECRET 'local-test',
            REGION '{REGION}', ENDPOINT '{endpoint}', URL_STYLE 'path', USE_SSL false)""")
        by_status = query_curated(con, release)

    write_summary(source, created, first, second, listing, rejected, by_status)
    print(f"wrote {OUT.relative_to(ROOT)}")


def write_summary(source, created, m, second, listing, rejected, by_status) -> None:
    release = m["release"]
    reasons = pd.Series(m["rejected_by_reason"], name="rows").rename_axis("reason").reset_index()
    flags = pd.Series(m["quality_flags"], name="rows").rename_axis("flag").reset_index()
    examples = (rejected.groupby("reject_reason").head(2)
                [["reject_reason", "transaction_id", "price", "date_of_transfer", "property_type"]])
    lines = [
        f"# Ingest summary: release {release}",
        "",
        "_Generated by `scripts/run_local.py` against the local moto S3 emulator._",
        "",
        "## Source",
        f"- File: HM Land Registry Price Paid Data, monthly update (Last-Modified {source['last_modified']})",
        f"- Size: {source['bytes']:,} bytes, SHA-256 `{source['sha256'][:16]}…`",
        f"- Landing object: `{m['source']}`",
        "",
        "## Event flow",
        f"- Buckets created this run: {', '.join(f'`{b}`' for b in created) or 'none (already existed)'}",
        f"- 1st event → **{m['status']}**",
        f"- 2nd, identical event (duplicate delivery) → **{second['status']}** ({second.get('why', '')})",
        "",
        "## Row counts",
        f"- Rows in: **{m['rows_in']:,}**",
        f"- Valid → curated Parquet: **{m['rows_valid']:,}** ({m['rows_valid'] / m['rows_in']:.2%})",
        f"- Rejected → quarantine: **{m['rows_rejected']:,}**",
        f"- Transfer dates in this release: {m['transfer_date_range'][0]} to {m['transfer_date_range'][1]}",
        "",
        "### Rejected rows by reason",
        reasons.to_markdown(index=False) if len(reasons) else "_None._",
        "",
    ]
    if len(examples):
        lines += ["Examples (address fields omitted):", "", examples.to_markdown(index=False), ""]
    lines += [
        "### Kept, but flagged for analysts",
        flags.to_markdown(index=False),
        "",
        "## Queried in place (DuckDB over S3, like Athena)",
        "Record status: A = added, C = changed, D = deleted.",
        "",
        by_status.to_markdown(index=False),
        "",
        "## Lake contents",
        listing.to_markdown(index=False),
        "",
        f"Curated Parquet is {m['outputs']['curated_bytes'] / m['source_bytes']:.1%} of the raw CSV size "
        "(and carries no street-level address).",
        "",
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
